### ISSUE TITLE
calc_consensus_haplo error when ncpus>=2

### ISSUE THREAD

**Issue by jeekinlau** [mmollina/mappoly2#2]
I constructed a map using BExMG and SWxBE and trying to integrate the two... in the calc_consensus_haplo() if i set ncpus=2 then it says, "Error in get(name, envir = envir) : object 'pedigree' not found"

ncpus=1 works fine. 

thanks

Jeekin

**Comment by mmollina** [comment]
@jeekinlau: The problem was a Windows-related issue. I tested it on my local MacOS. Please check if it is working now on your system. Thanks.

**Comment by jeekinlau** [comment]
This fixed it on my window system. thanks
